name: Sync Garmin To Global

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1,13 * * *'
  push:
    branches:
      - master
    paths:
      - run_page/garmin_sync.py
      - run_page/gpx_sync.py
      - run_page/tcx_sync.py
      - run_page/garmin_sync_cn_global.py
      - run_page/tcx_to_garmin_sync.py
      - run_page/garmin_to_strava_sync.py
      - requirements.txt

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync_cn_to_global:
    name: Sync Garmin Global
    uses: ./.github/workflows/run_data_sync.yml
    with:
      job_name: garmin_sync_cn_global
      make_svg: false
    secrets: inherit
